language: node_js

node_js:
  - '0.10'

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - npm install
  - npm install istanbul coveralls

env:
  global:
  - secure: "SF/JJ6H/l+t0UfNTifehsCAI2pmBz6yIKDPJIMLJEGSjCbonfiuPu6J6Jswkahg89didMbmFx/bztEPK5pbGNkBEadxMNh+t4KlbqID+C6pfbsuHWrCw7NO5p0anRCYBcsRvyY+j+w+Owlk4gEtB1ZA0B56mHVIxxRG+/HII0VU="
